version: "3.9"
services:
  api:
    build: .
    ports:
      - "9090:8080"
    volumes:
    # Enables hot reload by mapping workdir to container workdir
      - ./:/app
    environment:
        POSTGRES_DB: spring
        POSTGRES_USER: dementedearplug
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: database
  #Adding postgress
  database:
    build: postgres
    environment:
        POSTGRES_DB: spring
        POSTGRES_USER: dementedearplug
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: database
    ports:
      - "5432:5432"